services:
  snap-archive-server:
    image: quarkus/code-with-quarkus-jvm
    ports:
      - "8080"
    environment:
      - MONGO_DB_URL=mongodb://root:example@host.docker.internal:27017
    restart: unless-stopped
#    deploy:
#      mode: replicated
#      replicas: 2


